<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TracingAssertions.TUnit.Tests</RootNamespace>
    <AssemblyName>TracingAssertions.TUnit.Tests</AssemblyName>

    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/TracingAssertions.TUnit/TracingAssertions.TUnit.csproj" />
  </ItemGroup>

</Project>
